### ISSUE TITLE
ask  username/password of jira after crack 

### ISSUE THREAD

**Issue by ducna96** [jasonwzhy/docker-jira#1]
i can't login to jira after crack follow your guide, 
can you answer my question?

**Comment by JiangHeng12138** [comment]
Jira will let you register the admin user when installing

**Comment by ducna96** [comment]
i just follow your guide, copy file , but jira still active normaly. it request license key. how to fix it? where i wrong  step ?

**Comment by ducna96** [comment]
i just follow your guide, copy file , but jira still active normaly. it request license key. how to fix it? where i wrong  step ?
